name: Build Aseprite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get skia for aseprite
        run: |
          curl https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Linux-Release-x64-libc++.zip --output skia.zip
          mkdir $HOME/skia
          unzip skia.zip -d $HOME/skia
          
      - name: Install dependencies
        run: |
          sudo apt-get install -y g++ clang libc++-dev libc++abi-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
      
      - name: Clone Aseprite
        run: git clone --recursive https://github.com/aseprite/aseprite.git
        
      - name: Build aseprite
        run: |
          cd aseprite
          mkdir build
          cd build
          export CC=clang
          export CXX=clang++
          cmake \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
          -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$HOME/skia \
          -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
          -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
          -G Ninja \
          ..
          ninja aseprite

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: aseprite-build
          path: aseprite/build/
